config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/register', to: 'users#new'
  # get '/login', to: 'sessions#new'
  # post '/login', to: 'sessions#create'
  # get '/logout', to: 'sessions#destroy'
  # post '/auth/twitter/callback', to: 'sessions#create'
  post '/parties/:id/players', to: 'parties#update'
  post '/auth/twitter', as: :twitter_login
  get '/auth/twitter/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get '/search/players', to: 'searches#index'
  get '/players/:id', to: 'players#show'
  get 'parties/:id', to: 'parties#show'
  get '/party', to: 'parties#show'
  # resources :users, only: [:create] do
  #   resources :parties, only:[:show, :update, :destroy] do
  #     resources :players, only:[:show]
  #   end
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      # new_user.uid                = auth_info.uid
      # new_user.screen_name        = auth_info.extra.access_token.params[:screen_name]
      # new_user.oauth_token        = auth_info.extra.access_token.token
      # new_user.oauth_token_secret = auth_info.extra.access_token.secret
      # new_user.oauth_token        = auth_info.extra.access_token.params[:oauth_token]
      # new_user.oauth_token_secret = auth_info.info.access_token.params[:oauth_token_secret]
      new_user.uid                = auth_info.uid
      new_user.screen_name        = auth_info.extra.access_token.params[:screen_name]
      new_user.oauth_token        = auth_info.credentials[:token]
      new_user.oauth_token_secret = auth_info.credentials[:secret]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController

  before_action :current_user, only: [:show]

  def show
    if current_user
      party_info = PartyFacade.find_party_by_id(current_user.id)
      @party = party_info[0]
      @players = party_info[1]
    else
      flash[:notice] = 'you need to log in to view this page.'
      redirect_to root_path
    end
  end

  def update
    PartyService.update_player_party(current_user.id, params[:player_id])
    redirect_to '/party'
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def show
    @player = PlayerFacade.find_player_by_id(params[:id])
    if current_user
      @user = current_user.id
      @player_in_party = PartyFacade.player_in_party?(@user,params[:id])
    else
      @player_in_party = false
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
    if params[:search_by_name]
      @name = params[:search_by_name]
      @players = PlayerFacade.search_players_by_name(@name)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      flash[:success] = 'Account Successfully Created'
      redirect_to "/login"
    else
      flash[:error] = 'Invalid Entry'
      render 'new'
    end
  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<div class="container">
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand">Dungeonball</a>

    <div id="search_bar">
      <%= form_with url: '/search/players', method: :get, local: true do |f| %>
      <%= f.label :search_by_name %>
      <%= f.text_field :search_by_name, placeholder: 'Search by player name' %>
      <%= f.submit 'Search' %>
      <% end %>
    </div>


</nav>
<% if current_user %>
Hello, <%= current_user.screen_name %>
<%= link_to "My Party", party_path, method: :get %>
<%= link_to "Logout", signout_path, method: :get %>
<% else %>
<%= link_to "Sign in with Twitter", twitter_login_path, method: :post %>
<% end %>
</div>

app/views/layouts/_player_ability_scores.erb
<div class="list-group">
  <a href="#" class="list-group-item list-group-item-action active">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">Why <%= @player.class %>?</h5>
      <small></small>
    </div>
    <p class="mb-1"></p>
    <small><%= @player.description %></small>
  </a>
  <a href="#" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">Strength: <%= @player.strength %></h5>
      <small class="text-muted">STR</small>
    </div>
    <p class="mb-1"></p>
    <small class="text-muted"></small>
  </a>
  <a href="#" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">Dexterity: <%= @player.dexterity %></h5>
      <small class="text-muted">DEX</small>
    </div>
    <p class="mb-1"></p>
    <small class="text-muted"></small>
  </a>
  <a href="#" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">Constitution: <%= @player.constitution %></h5>
      <small class="text-muted">CON</small>
    </div>
    <p class="mb-1"></p>
    <small class="text-muted"></small>
  </a>
  <a href="#" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">Intelligence: <%= @player.intelligence %></h5>
      <small class="text-muted">INT</small>
    </div>
    <p class="mb-1"></p>
    <small class="text-muted"></small>
  </a>
  <a href="#" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">Wisdom: <%= @player.wisdom %></h5>
      <small class="text-muted">WIS</small>
    </div>
    <p class="mb-1"></p>
    <small class="text-muted"></small>
  </a>
  <a href="#" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">Charisma: <%= @player.charisma %></h5>
      <small class="text-muted">CHA</small>
    </div>
    <p class="mb-1"></p>
    <small class="text-muted"></small>
  </a>
  <a href="#" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">Proficiencies:</h5><br/>
    </div>
    <p class="mb-1"></p>
    <small class="text-muted">
      <ul>
        <% @player.proficiencies.each do |p| %>
        <small><li><%= p.to_s %></li></small>
        <% end %>
      </ul>
    </small>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Dungeonball</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
  </head>

  <body>

    <%= render "/layouts/navbar" %>
    <% flash.each do |name, msg| %>
    <div class="alert alert-danger" role="alert">
      <%= content_tag :div, msg, class:name %>

    </div>
    <% end %>
    <center>
      <div class="jumbotron jumbotron-fluid">
      <h1 class="animate__animated animate__swing">Dungeonball</h1>

    </div>
    </center>
    <br/>
    <%= yield %>
  </body>
</html>

app/views/parties/show.html.erb
<h1><%=  @party.name %></h1>
<ol>
<%@players.each do |player|%>
    <li><%= link_to "#{player[:name]}", "/players/#{player[:id]}", method: :get %></li>
<%end%>
</ol>

app/views/players/show.html.erb
<div class="container">
  <h1><%= @player.name %></h1><br/>
  <h3>Class: <%= @player.class %></h3>
  <%= render "/layouts/player_ability_scores" %>


  <% if current_user %>
    <% if !PartyFacade.player_in_party?(current_user.id, @player.id) %>
      <%= button_to "Add Player to My Party", "/parties/#{current_user.id}/players", params: {player_id: @player.id}, method: :post, local: true %>
      <% else %>
      <p>Party Member</p>
    <% end %>
    <% else %>
      <%= link_to "Sign in with Twitter to add this player to your party", twitter_login_path, method: :post %>
  <% end %>
</div>

app/views/searches/index.html.erb
<div class="container">
  <% if @players.length > 0 %>
  <ul>
    <%@players.each do |player|%>
    <li><h3><%= link_to "#{player.name}", "/players/#{player.id}"%></h3></li>
    <%end%>
  </ul>

  <% else %>
  <h3>Sorry, no results match your search. Try Again!</h3>
  <% end %>
</div>